package by.myproject.news.controller;

public enum CommandName {
	
	REGISTRATION_PAGE, 
	AUTHORIZATION_PAGE,
	REGISTRATION_NEW_USER,
	UNKNOWN_COMMAND, 
	AUTHORIZATION_USER,
	GO_TO_MAIN_PAGE,
	AFTER_AUTHORIZATION,//Пока не используется
	CHANGE_LOCAL,
	GO_TO_USER_PAGE, 
	LOGOUT, 
	GO_TO_USER_SETUP_PAGE,
	GO_TO_CONTENT_NEWS_PAGE,
	GO_TO_CREATE_NEWS_PAGE,
	CREATE_NEW_NEWS,
	CHANGE_DATA,
	GO_TO_CHANGE_DATA_PAGE,
	GO_TO_LAST_PAGE,
	GO_TO_ADMIN_PAGE,
	GO_TO_CORRECTION_NEWS_PAGE,
	DELETE_NEWS,
	SEND_TO_СORRECT,
	PUBLISH_NEWS,
	APPEND_COMMENT_NEWS,
	GO_TO_LIST_USERS_PAGE,
	DELETE_USER
}
